library(tidyverse)
library(lubridate)
data <- read.csv2("household_power_consumption.txt")
req1 <- data[ 66637:69517, ]
req2 <- transform(req1, Global_active_power = as.numeric(Global_active_power))
req <- req2 %>% mutate_at(vars(3:9), as.numeric)
req$Date <- as.Date(req$Date, format = "%d/%m/%Y")
req$Datetime <- paste(req$Date, req$Time, sep = " ") 
req$Datetime <- strptime(req$Datetime, format = "%Y-%m-%d %H:%M:%S")
req$Datetime <- as.POSIXct(req$Datetime)
png("plot3.png", width = 480, height = 480)
with(req, plot( Datetime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(req, lines( Datetime, Sub_metering_2, type = "l", col = "red"))
with(req, lines( Datetime, Sub_metering_3, type = "l", col = "blue"))
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, cex = 0.8)
dev.off()