library(tidyverse)
library(lubridate)
data <- read.csv2("household_power_consumption.txt")
req1 <- data[ 66637:69517, ]
req2 <- transform(req1, Global_active_power = as.numeric(Global_active_power))
req <- req2 %>% mutate_at(vars(3:9), as.numeric)
req$Date <- as.Date(req$Date, format = "%d/%m/%Y")
req$Datetime <- paste(req$Date, req$Time, sep = " ") 
req$Datetime <- strptime(req$Datetime, format = "%Y-%m-%d %H:%M:%S")
req$Datetime <- as.POSIXct(req$Datetime)
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
with(req, plot(Datetime, Global_active_power, type = "l", xlab = ""))
with(req, plot(Datetime, Voltage, type = "l", xlab = "datetime"))
with(req, plot( Datetime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(req, lines( Datetime, Sub_metering_2, type = "l", col = "red"))
with(req, lines( Datetime, Sub_metering_3, type = "l", col = "blue"))
legend("topright", inset = .02, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, box.lty = 0, cex = 0.8)
with(req, plot(Datetime, Global_reactive_power, type = "l", xlab = "datetime"))
dev.off()